### ISSUE TITLE
stats should be in heap struct not size class

### ISSUE THREAD

**Issue by rachelyeshurun** [yigalalexander/ex12#2]
I don't agree with this structure. I think we need to keep track of mem used in all the superblocks of the heap no matter in which size class.

typedef struct ssizeclass {

```
unsigned int mSize;
pthread_mutex_t mutex;
size_t totat_size;
size_t total_used;
SuperBlockList super_blocks_list;
```

} SizeClass;

**Comment by yigalalexander** [comment]
Why not at both locations?

**Comment by rachelyeshurun** [comment]
why both? stats are heap stats. a(i), u(i) where i is a heap

**Comment by yigalalexander** [comment]
Thanks
